# Generated by Django 4.2 on 2023-08-18 02:00

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cords', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('rate', models.FloatField(null=True)),
                ('text', models.CharField(default=False, max_length=255, null=True)),
                ('air', models.BooleanField(default=False, null=True)),
                ('green', models.BooleanField(default=False, null=True)),
                ('urban', models.BooleanField(default=False, null=True)),
                ('clear', models.BooleanField(default=False, null=True)),
                ('water', models.BooleanField(default=False, null=True)),
                ('photo', models.ImageField(null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequsetStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TrashOrganizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('address_hash', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.trashorganizations')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.complaint')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.requsetstatus')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raiting', models.IntegerField(default=3)),
                ('eco_scores', models.IntegerField(default=0)),
                ('permition_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Api.permition')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Api.complaintstatus'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
