version: "3.9"

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.88.0/24
          gateway: 192.168.88.1

services:
  db:
    container_name: db
    build:
      context: ./postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/
    # environment:
      # - "POSTGRES_USER=lalala"
      # - "POSTGRES_PASSWORD=hahaha"
      # - "POSTGRES_DB=dadada"
    ports:
      - 6543:5432
    networks:
      net:
        ipv4_address: 192.168.88.101
  
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    networks:
      net:
        ipv4_address: 192.168.88.102
    # environment:
    #   - SECRET_KEY
    depends_on:
      - db
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    networks:
      net:
        ipv4_address: 192.168.88.103
    depends_on:
      - backend
  
  # nginx:
    # container_name: nginx
    # build:
      # context: ./nginx
    # ports:
      # - 8088:80
    # networks:
      # net:
        # ipv4_address: 192.168.88.104
    # volumes:
      # - ./nginx/static:/usr/share/nginx/html

